// Code generated by protoc-gen-go. DO NOT EDIT.
// source: osi_datarecording.proto

package osi3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// \brief (Time) Series of \c SensorData messages that may be used for data
// recording or internal buffering by some sensor models.
//
type SensorDataSeries struct {
	// List of sensor data messages for subsequent timesteps.
	//
	// \note OSI uses singular instead of plural for repeated field names.
	//
	SensorData           []*SensorData `protobuf:"bytes,1,rep,name=sensor_data,json=sensorData,proto3" json:"sensor_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SensorDataSeries) Reset()         { *m = SensorDataSeries{} }
func (m *SensorDataSeries) String() string { return proto.CompactTextString(m) }
func (*SensorDataSeries) ProtoMessage()    {}
func (*SensorDataSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da40bc55a7679dc, []int{0}
}

func (m *SensorDataSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorDataSeries.Unmarshal(m, b)
}
func (m *SensorDataSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorDataSeries.Marshal(b, m, deterministic)
}
func (m *SensorDataSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorDataSeries.Merge(m, src)
}
func (m *SensorDataSeries) XXX_Size() int {
	return xxx_messageInfo_SensorDataSeries.Size(m)
}
func (m *SensorDataSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorDataSeries.DiscardUnknown(m)
}

var xxx_messageInfo_SensorDataSeries proto.InternalMessageInfo

func (m *SensorDataSeries) GetSensorData() []*SensorData {
	if m != nil {
		return m.SensorData
	}
	return nil
}

//
// \brief List of sensors where each element contains a time series of
// \c SensorData messages.
//
type SensorDataSeriesList struct {
	// List of sensor data for multiple sensors at subsequent timesteps.
	//
	// \note OSI uses singular instead of plural for repeated field names.
	//
	Sensor               []*SensorDataSeries `protobuf:"bytes,1,rep,name=sensor,proto3" json:"sensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SensorDataSeriesList) Reset()         { *m = SensorDataSeriesList{} }
func (m *SensorDataSeriesList) String() string { return proto.CompactTextString(m) }
func (*SensorDataSeriesList) ProtoMessage()    {}
func (*SensorDataSeriesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6da40bc55a7679dc, []int{1}
}

func (m *SensorDataSeriesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorDataSeriesList.Unmarshal(m, b)
}
func (m *SensorDataSeriesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorDataSeriesList.Marshal(b, m, deterministic)
}
func (m *SensorDataSeriesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorDataSeriesList.Merge(m, src)
}
func (m *SensorDataSeriesList) XXX_Size() int {
	return xxx_messageInfo_SensorDataSeriesList.Size(m)
}
func (m *SensorDataSeriesList) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorDataSeriesList.DiscardUnknown(m)
}

var xxx_messageInfo_SensorDataSeriesList proto.InternalMessageInfo

func (m *SensorDataSeriesList) GetSensor() []*SensorDataSeries {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func init() {
	proto.RegisterType((*SensorDataSeries)(nil), "osi3.SensorDataSeries")
	proto.RegisterType((*SensorDataSeriesList)(nil), "osi3.SensorDataSeriesList")
}

func init() { proto.RegisterFile("osi_datarecording.proto", fileDescriptor_6da40bc55a7679dc) }

var fileDescriptor_6da40bc55a7679dc = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x2f, 0xce, 0x8c,
	0x4f, 0x49, 0x2c, 0x49, 0x2c, 0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0xc9, 0xcc, 0x4b, 0xd7, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x2f, 0xce, 0x34, 0x96, 0x12, 0x01, 0x49, 0x17, 0xa7, 0xe6,
	0x15, 0xe7, 0x17, 0x81, 0x14, 0x41, 0xe4, 0x94, 0x5c, 0xb9, 0x04, 0x82, 0xc1, 0x62, 0x2e, 0x89,
	0x25, 0x89, 0xc1, 0xa9, 0x45, 0x99, 0xa9, 0xc5, 0x42, 0x86, 0x5c, 0xdc, 0x10, 0x75, 0x60, 0xd3,
	0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x04, 0xf4, 0x40, 0xa6, 0xe8, 0x21, 0x14, 0x07, 0x71,
	0x15, 0xc3, 0xd9, 0x4a, 0x6e, 0x5c, 0x22, 0xe8, 0xc6, 0xf8, 0x64, 0x16, 0x97, 0x08, 0xe9, 0x71,
	0xb1, 0x41, 0x54, 0x41, 0x4d, 0x11, 0x43, 0x37, 0x05, 0xa2, 0x36, 0x08, 0xaa, 0xca, 0x89, 0xc9,
	0x83, 0x31, 0x89, 0x0d, 0xec, 0x32, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x24, 0x5c,
	0x02, 0xd0, 0x00, 0x00, 0x00,
}
