// Code generated by protoc-gen-go. DO NOT EDIT.
// source: osi_version.proto

package osi3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// \brief The interface version number.
//
// The field denoting the version number. This needs to be set by the
// sender to the actual OSI version that is to be sent.  Code wanting to
// access the version number of the OSI code base can access a FileOptions,
// which has the proper values, like this:
//
// @code
// auto currentInterfaceVersion =
//   InterfaceVersion::descriptor()->file()->options().GetExtension(current_interface_version);
// @endcode
//
// If a message with all components set to the default value 0 is
// received, this indicates that either that the message was sent by
// a version 2.2.0 or earlier release, or that the sender did not
// properly set the version components prior to sending.
//
// Increments will happen as part of changes to the whole interface.
// The meaning of different InterfaceVersions is defined [1].
//
// \par References:
// [1] Open Simulation Interface: README.md
type InterfaceVersion struct {
	// Major version number.
	//
	VersionMajor uint32 `protobuf:"varint,1,opt,name=version_major,json=versionMajor,proto3" json:"version_major,omitempty"`
	// Minor version number.
	//
	VersionMinor uint32 `protobuf:"varint,2,opt,name=version_minor,json=versionMinor,proto3" json:"version_minor,omitempty"`
	// Patch version number.
	//
	VersionPatch         uint32   `protobuf:"varint,3,opt,name=version_patch,json=versionPatch,proto3" json:"version_patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceVersion) Reset()         { *m = InterfaceVersion{} }
func (m *InterfaceVersion) String() string { return proto.CompactTextString(m) }
func (*InterfaceVersion) ProtoMessage()    {}
func (*InterfaceVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6ee6b99c9662cbc, []int{0}
}

func (m *InterfaceVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceVersion.Unmarshal(m, b)
}
func (m *InterfaceVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceVersion.Marshal(b, m, deterministic)
}
func (m *InterfaceVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceVersion.Merge(m, src)
}
func (m *InterfaceVersion) XXX_Size() int {
	return xxx_messageInfo_InterfaceVersion.Size(m)
}
func (m *InterfaceVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceVersion.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceVersion proto.InternalMessageInfo

func (m *InterfaceVersion) GetVersionMajor() uint32 {
	if m != nil {
		return m.VersionMajor
	}
	return 0
}

func (m *InterfaceVersion) GetVersionMinor() uint32 {
	if m != nil {
		return m.VersionMinor
	}
	return 0
}

func (m *InterfaceVersion) GetVersionPatch() uint32 {
	if m != nil {
		return m.VersionPatch
	}
	return 0
}

var E_CurrentInterfaceVersion = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*InterfaceVersion)(nil),
	Field:         81000,
	Name:          "osi3.current_interface_version",
	Tag:           "bytes,81000,opt,name=current_interface_version",
	Filename:      "osi_version.proto",
}

func init() {
	proto.RegisterType((*InterfaceVersion)(nil), "osi3.InterfaceVersion")
	proto.RegisterExtension(E_CurrentInterfaceVersion)
}

func init() { proto.RegisterFile("osi_version.proto", fileDescriptor_c6ee6b99c9662cbc) }

var fileDescriptor_c6ee6b99c9662cbc = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x2f, 0xce, 0x8c,
	0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9,
	0x2f, 0xce, 0x34, 0x96, 0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95,
	0xa6, 0xe9, 0xa7, 0xa4, 0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0xd4, 0x29, 0x35,
	0x32, 0x72, 0x09, 0x78, 0xe6, 0x95, 0xa4, 0x16, 0xa5, 0x25, 0x26, 0xa7, 0x86, 0x41, 0x8c, 0x10,
	0x52, 0xe6, 0xe2, 0x85, 0x9a, 0x16, 0x9f, 0x9b, 0x98, 0x95, 0x5f, 0x24, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x1b, 0xc4, 0x03, 0x15, 0xf4, 0x05, 0x89, 0xa1, 0x28, 0xca, 0xcc, 0xcb, 0x2f, 0x92, 0x60,
	0x42, 0x55, 0x04, 0x12, 0x43, 0x56, 0x54, 0x90, 0x58, 0x92, 0x9c, 0x21, 0xc1, 0x8c, 0xa2, 0x28,
	0x00, 0x24, 0x66, 0x55, 0xc4, 0x25, 0x99, 0x5c, 0x5a, 0x54, 0x94, 0x9a, 0x57, 0x12, 0x9f, 0x09,
	0x73, 0x0a, 0xcc, 0x3b, 0x42, 0x32, 0x7a, 0x10, 0x3f, 0xe8, 0xc1, 0xfc, 0xa0, 0xe7, 0x96, 0x99,
	0x93, 0xea, 0x5f, 0x50, 0x92, 0x99, 0x9f, 0x57, 0x2c, 0xf1, 0xe2, 0x07, 0x8b, 0x02, 0xa3, 0x06,
	0xb7, 0x91, 0x98, 0x1e, 0xc8, 0xbf, 0x7a, 0xe8, 0x3e, 0x09, 0x12, 0x87, 0x1a, 0x8c, 0x2e, 0xe1,
	0x24, 0x72, 0xe8, 0x98, 0x3a, 0x13, 0x07, 0x33, 0x88, 0x14, 0x60, 0x00, 0x91, 0x12, 0x8c, 0x1e,
	0x8c, 0x49, 0x6c, 0x60, 0x4b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xcb, 0xa0, 0x59,
	0x51, 0x01, 0x00, 0x00,
}
