// Code generated by protoc-gen-go. DO NOT EDIT.
// source: osi_sensorspecific.proto

package osi3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// \brief Message encapsulates all data for detected objects that is specific to
// radar sensors.
//
type RadarSpecificObjectData struct {
	// The radar cross section (RCS) of the detected object.
	//
	// Unit: [dB m^2]
	//
	Rcs                  float64  `protobuf:"fixed64,1,opt,name=rcs,proto3" json:"rcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RadarSpecificObjectData) Reset()         { *m = RadarSpecificObjectData{} }
func (m *RadarSpecificObjectData) String() string { return proto.CompactTextString(m) }
func (*RadarSpecificObjectData) ProtoMessage()    {}
func (*RadarSpecificObjectData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e08d0e0b881cde8, []int{0}
}

func (m *RadarSpecificObjectData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadarSpecificObjectData.Unmarshal(m, b)
}
func (m *RadarSpecificObjectData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadarSpecificObjectData.Marshal(b, m, deterministic)
}
func (m *RadarSpecificObjectData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadarSpecificObjectData.Merge(m, src)
}
func (m *RadarSpecificObjectData) XXX_Size() int {
	return xxx_messageInfo_RadarSpecificObjectData.Size(m)
}
func (m *RadarSpecificObjectData) XXX_DiscardUnknown() {
	xxx_messageInfo_RadarSpecificObjectData.DiscardUnknown(m)
}

var xxx_messageInfo_RadarSpecificObjectData proto.InternalMessageInfo

func (m *RadarSpecificObjectData) GetRcs() float64 {
	if m != nil {
		return m.Rcs
	}
	return 0
}

//
// \brief Message encapsulates all data for detected objects that is specific to
// lidar sensors.
//
type LidarSpecificObjectData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LidarSpecificObjectData) Reset()         { *m = LidarSpecificObjectData{} }
func (m *LidarSpecificObjectData) String() string { return proto.CompactTextString(m) }
func (*LidarSpecificObjectData) ProtoMessage()    {}
func (*LidarSpecificObjectData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e08d0e0b881cde8, []int{1}
}

func (m *LidarSpecificObjectData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LidarSpecificObjectData.Unmarshal(m, b)
}
func (m *LidarSpecificObjectData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LidarSpecificObjectData.Marshal(b, m, deterministic)
}
func (m *LidarSpecificObjectData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LidarSpecificObjectData.Merge(m, src)
}
func (m *LidarSpecificObjectData) XXX_Size() int {
	return xxx_messageInfo_LidarSpecificObjectData.Size(m)
}
func (m *LidarSpecificObjectData) XXX_DiscardUnknown() {
	xxx_messageInfo_LidarSpecificObjectData.DiscardUnknown(m)
}

var xxx_messageInfo_LidarSpecificObjectData proto.InternalMessageInfo

//
// \brief Message encapsulates all data for detected objects that is specific to
// camera sensors.
//
type CameraSpecificObjectData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraSpecificObjectData) Reset()         { *m = CameraSpecificObjectData{} }
func (m *CameraSpecificObjectData) String() string { return proto.CompactTextString(m) }
func (*CameraSpecificObjectData) ProtoMessage()    {}
func (*CameraSpecificObjectData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e08d0e0b881cde8, []int{2}
}

func (m *CameraSpecificObjectData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraSpecificObjectData.Unmarshal(m, b)
}
func (m *CameraSpecificObjectData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraSpecificObjectData.Marshal(b, m, deterministic)
}
func (m *CameraSpecificObjectData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraSpecificObjectData.Merge(m, src)
}
func (m *CameraSpecificObjectData) XXX_Size() int {
	return xxx_messageInfo_CameraSpecificObjectData.Size(m)
}
func (m *CameraSpecificObjectData) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraSpecificObjectData.DiscardUnknown(m)
}

var xxx_messageInfo_CameraSpecificObjectData proto.InternalMessageInfo

//
// \brief Message encapsulates all data for detected objects that is specific to
// ultrasonic sensors.
//
type UltrasonicSpecificObjectData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UltrasonicSpecificObjectData) Reset()         { *m = UltrasonicSpecificObjectData{} }
func (m *UltrasonicSpecificObjectData) String() string { return proto.CompactTextString(m) }
func (*UltrasonicSpecificObjectData) ProtoMessage()    {}
func (*UltrasonicSpecificObjectData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e08d0e0b881cde8, []int{3}
}

func (m *UltrasonicSpecificObjectData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UltrasonicSpecificObjectData.Unmarshal(m, b)
}
func (m *UltrasonicSpecificObjectData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UltrasonicSpecificObjectData.Marshal(b, m, deterministic)
}
func (m *UltrasonicSpecificObjectData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UltrasonicSpecificObjectData.Merge(m, src)
}
func (m *UltrasonicSpecificObjectData) XXX_Size() int {
	return xxx_messageInfo_UltrasonicSpecificObjectData.Size(m)
}
func (m *UltrasonicSpecificObjectData) XXX_DiscardUnknown() {
	xxx_messageInfo_UltrasonicSpecificObjectData.DiscardUnknown(m)
}

var xxx_messageInfo_UltrasonicSpecificObjectData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RadarSpecificObjectData)(nil), "osi3.RadarSpecificObjectData")
	proto.RegisterType((*LidarSpecificObjectData)(nil), "osi3.LidarSpecificObjectData")
	proto.RegisterType((*CameraSpecificObjectData)(nil), "osi3.CameraSpecificObjectData")
	proto.RegisterType((*UltrasonicSpecificObjectData)(nil), "osi3.UltrasonicSpecificObjectData")
}

func init() { proto.RegisterFile("osi_sensorspecific.proto", fileDescriptor_2e08d0e0b881cde8) }

var fileDescriptor_2e08d0e0b881cde8 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc8, 0x2f, 0xce, 0x8c,
	0x2f, 0x4e, 0xcd, 0x2b, 0xce, 0x2f, 0x2a, 0x2e, 0x48, 0x4d, 0xce, 0x4c, 0xcb, 0x4c, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x2f, 0xce, 0x34, 0x56, 0xd2, 0xe6, 0x12, 0x0f, 0x4a,
	0x4c, 0x49, 0x2c, 0x0a, 0x86, 0x4a, 0xfa, 0x27, 0x65, 0xa5, 0x26, 0x97, 0xb8, 0x24, 0x96, 0x24,
	0x0a, 0x09, 0x70, 0x31, 0x17, 0x25, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x06, 0x81, 0x98,
	0x4a, 0x92, 0x5c, 0xe2, 0x3e, 0x99, 0x58, 0x15, 0x2b, 0x49, 0x71, 0x49, 0x38, 0x27, 0xe6, 0xa6,
	0x16, 0x25, 0x62, 0x91, 0x93, 0xe3, 0x92, 0x09, 0xcd, 0x29, 0x29, 0x4a, 0x2c, 0xce, 0xcf, 0xcb,
	0x4c, 0xc6, 0x94, 0x77, 0x62, 0xf2, 0x60, 0x4c, 0x62, 0x03, 0x3b, 0xca, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x9c, 0x41, 0x5a, 0xba, 0xb0, 0x00, 0x00, 0x00,
}
